/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AInput: typeof import('./src/components/form/AInput.vue')['default']
    CarouselSlide: typeof import('./src/components/common/CarouselSlide.vue')['default']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    Footer: typeof import('./src/components/common/Footer.vue')['default']
    FooterComponent: typeof import('./src/components/common/FooterComponent.vue')['default']
    HeaderMenu: typeof import('./src/components/common/HeaderMenu.vue')['default']
    ProductCard: typeof import('./src/components/product/ProductCard.vue')['default']
    ProductCart: typeof import('./src/components/product/ProductCart.vue')['default']
    ProductList: typeof import('./src/components/product/ProductList.vue')['default']
    ProductReview: typeof import('./src/components/product/ProductReview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./src/components/common/SearchInput.vue')['default']
  }
}
