/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AInput: typeof import('./src/components/form/AInput.vue')['default']
    ApplicationManagement: typeof import('./src/components/developer/ApplicationManagement.vue')['default']
    CarouselSlide: typeof import('./src/components/common/CarouselSlide.vue')['default']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElRow: typeof import('element-plus/es')['ElRow']
    FooterComponent: typeof import('./src/components/common/FooterComponent.vue')['default']
    HeaderMenu: typeof import('./src/components/common/HeaderMenu.vue')['default']
    PersonalInformation: typeof import('./src/components/developer/PersonalInformation.vue')['default']
    ProductAddForm: typeof import('./src/components/developer/ProductAddForm.vue')['default']
    ProductCard: typeof import('./src/components/product/ProductCard.vue')['default']
    ProductDetailAddForm: typeof import('./src/components/developer/ProductDetailAddForm.vue')['default']
    ProductDetails: typeof import('./src/components/developer/ProductDetails.vue')['default']
    ProductDetailUpdateForm: typeof import('./src/components/developer/ProductDetailUpdateForm.vue')['default']
    ProductList: typeof import('./src/components/product/ProductList.vue')['default']
    ProductReview: typeof import('./src/components/product/ProductReview.vue')['default']
    ProductUpdateForm: typeof import('./src/components/developer/ProductUpdateForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./src/components/common/SearchInput.vue')['default']
    StaffManagement: typeof import('./src/components/developer/StaffManagement.vue')['default']
    Statistic: typeof import('./src/components/developer/Statistic.vue')['default']
    ThemeSwitcher: typeof import('./src/components/common/ThemeSwitcher.vue')['default']
  }
}
